#!/bin/bash

# Journal file location
JOURNAL_DIR=/home/stormrider/var/log
JOURNAL_FILE=$(date +%Y%m%d)
JOURNAL=$JOURNAL_DIR/$JOURNAL_FILE

# Create and load today's journal file if doesn't exist
if [ ! -f "$JOURNAL" ]; then
	touch "$JOURNAL"
	banner motd > "$JOURNAL"
	echo "*** personal journal of stormrider" >> "$JOURNAL"
	date >> "$JOURNAL"
	ddate >> "$JOURNAL"
	fortune -s fortunes >> "$JOURNAL"
	echo " " >> "$JOURNAL"
	echo "*** daily journal" >> "$JOURNAL"

fi

# Open journal file in vim
vi "$JOURNAL"
