#!/bin/bash

# Journal file location
JOURNAL_DIR=/home/stormrider/var/log
JOURNAL_FILE=$(date +%Y%m%d)
JOURNAL=$JOURNAL_DIR/$JOURNAL_FILE

# Create today's journal file if doesn't exist
if [ ! -f "$JOURNAL" ]; then
  touch "$JOURNAL"
fi

# Open journal file in vim
vi "$JOURNAL"
