#!/bin/bash

# Journal file location
JOURNAL_DIR=/home/stormrider/var/log
JOURNAL_FILE=$(date +%Y%m%d)
JOURNAL=$JOURNAL_DIR/$JOURNAL_FILE

# Create today's journal file if doesn't exist
if [ ! -f "$JOURNAL" ]; then
  touch "$JOURNAL"
fi

# Front-load today's journal file
banner motd > "$JOURNAL"
echo "*** personal journal of stormrider" >> "$JOURNAL"
date >> "$JOURNAL"
ddate >> "$JOURNAL"
fortune -s fortunes >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** appointments" >> "$JOURNAL"
calendar -A0 | grep "@appt" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** gotta-dos" >> "$JOURNAL"
calendar -A0 | grep "@gotta" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** wanna-dos" >> "$JOURNAL"
calendar -A0 | grep "@wanna" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** work things" >> "$JOURNAL"
calendar -A0 | grep "@work" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** home stuff" >> "$JOURNAL"
calendar -A0 | grep "@home" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** daily habits" >> "$JOURNAL"
calendar -A0 | grep "@habit" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** other things to do" >> "$JOURNAL"
calendar -A0 | grep -v "@appt" | grep -v "@gotta" | grep -v "@wanna" | grep -v "@work" | grep -v "@home" | grep -v "@habit" >> "$JOURNAL"
echo " " >> "$JOURNAL"
echo "*** daily journal" >> "$JOURNAL"

# Open journal file in vim
vi "$JOURNAL"
